name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job:
    runs-on: windows-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi
        run: echo "hello"